### ISSUE TITLE
Page Type migration fails when using inherited page types

### ISSUE THREAD

**Issue by mcbeev** [Kentico/xperience-migration-toolkit#37]
### Brief bug description

Using the migrate command fails to migrate all page types in cases where inherited page types are used (some still work depending on order of the page types returned).

### Repro steps

1. Create a new page type in a KX13 source database as a normal page type 'Home', fields don't matter
2. Create a new page type in same database as a normal page type 'Base', fields don't really matter
3. Change Home to Inherit from Base.
4. Run the migration command for just pages types and pages (or any other simple config) like `migrate --siteId 2 --culture en-US --sites --users --page-types --pages` 
5. See error

### Expected behavior

Correct behavior would be to handle the situation not based on the Order of the ClassID but instead try to process the entire result set to find the "base" inherited Page Type for any Page Type that uses Inheritance.

### Test environment

 - Platform/OS: .NET 6, Windows
 - Version: this repo's main branch

### Additional context

An example log that shows the error:
```
2022-07-08T10:54:08.2083696-04:00  [WRN] Mapping "Migration.Toolkit.KX13.Models.CmsClass" primary key: 5510 failed, "Sequence contains no elements" (ecc18f30)
2022-07-08T10:54:08.2141618-04:00  [ERR] NeedManualAction: True, ReferenceName: MissingRequiredDependency, AdditionalInfo: DependencyType: CmsClass, FieldName: ClassId, SourceValue: 5510 (5a57336f)
2022-07-08T10:54:08.2144640-04:00  [ERR] Error while saving page type "McBeev.HomeNode" (d6bf0613)
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'mapped')
   at Migration.Toolkit.Core.Handlers.MigratePageTypesCommandHandler.SaveUsingKxoApi(CmsClass kx13Class, DataClassInfo kxoDataClass) in C:\XbKMigrationToolkit\kx13-to-kxo-migration\Migration.Toolkit.Core\Handlers\MigratePageTypesCommandHandler.cs:line 182
2022-07-08T10:54:08.2179811-04:00  [WRN] Mapping "Migration.Toolkit.KX13.Models.CmsClass" primary key: 5513 failed, "Sequence contains no elements" (ecc18f30)
2022-07-08T10:54:08.2188951-04:00  [ERR] NeedManualAction: True, ReferenceName: MissingRequiredDependency, AdditionalInfo: DependencyType: CmsClass, FieldName: ClassId, SourceValue: 5513 (5bc1b678)
2022-07-08T10:54:08.2189670-04:00  [ERR] Error while saving page type "McBeev.MenuItemNode" (d6bf0613)
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'mapped')
   at Migration.Toolkit.Core.Handlers.MigratePageTypesCommandHandler.SaveUsingKxoApi(CmsClass kx13Class, DataClassInfo kxoDataClass) in C:\XbKMigrationToolkit\kx13-to-kxo-migration\Migration.Toolkit.Core\Handlers\MigratePageTypesCommandHandler.cs:line 182
```

Notice how HomeNode is asking for a base node of 5510 (which should resolve to the correct BaseNode page type) but instead errors.

### Screenshots

Add links to screenshots, if possible.
![image](https://user-images.githubusercontent.com/9918767/178036893-f3e0339c-c849-4fb1-beb3-93f6d1e0c47c.png)

**Comment by mcbeev** [comment]
Thanks @tkrch. Related note, I have yet to get any pages actually migrate. Just many many errors. Even if I exclude multiple Page Types like this that were erroring. I was planning on waiting to see if this issue gets fixed, then to try again. But I'm not sure it's related. But as soon as the fix is in I will go back to it.
